[relaychain]
default_command = "./target/polkadot"
chain = "rococo-local"

[[relaychain.nodes]]
name = "validator1"
validator = true
rpc_port = 9944

[[relaychain.nodes]]
name = "validator2"
validator = true
rpc_port = 9955

[[parachains]]
id = 1000
chain_spec_path = "./chain_spec.json"

[parachains.collator]
name = "collator1"
rpc_port = 9988
command = "polkadot-omni-node"

